### ISSUE TITLE
How to setup and build ONNC 

### ISSUE THREAD

**Issue by ccu1tn** [ONNC/onnc-umbrella#16]
Hi everyone. I am just beginning for study ONNC. I want to study it. But i don't know how is install it and build it. 
Please, Tell me step by step to do it.
(Ex. What I must download? and then...)
Thank for everyone help me.

**Comment by ccu1tn** [comment]
Thank you so much for support to me. Do you have vision for Window?

**Comment by LuisHsu** [comment]
Not priority.
