### ISSUE TITLE
JSON/JsonScanner.cpp is missing 

### ISSUE THREAD

**Issue by evenpengqnap** [ONNC/onnc-umbrella#3]
I was building with command `./build.sh normal ../build-onnc-unbrella/`.
The compilation failed with following message.
Please help to resolve it, thanks!

```
g++ -DHAVE_CONFIG_H   -I/workspace/onnc-umbrella/src/include  -I/workspace/onnc-umbrella/build-normal/include  -I/workspace/onnc-umbrella/build-normal/lib -I/workspace/onnc-umbrella/onncroot/include -I/workspace/onnc-umbrella/src/lib/Target -I/workspace/onnc-umbrella/src/lib/Target/Sophon -I/workspace/onnc-umbrella/src/lib/Target/Sophon/include -Waddress -Wchar-subscripts -Wcomment -Wformat -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wstrict-aliasing -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunknown-pragmas -Wunused-function -Wunused-label -Wunused-value -Wunused-variable -Wvolatile-register-var -Wno-return-stack-address     -g -O2 -MT JSON/JsonScanner.o -MD -MP -MF $depbase.Tpo -c -o JSON/JsonScanner.o JSON/JsonScanner.cpp &&\
mv -f $depbase.Tpo $depbase.Po
g++: error: JSON/JsonScanner.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
Makefile:2277: recipe for target 'JSON/JsonScanner.o' failed
make[1]: *** [JSON/JsonScanner.o] Error 1
make[1]: Leaving directory '/workspace/onnc-umbrella/build-normal/lib'
Makefile:532: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
[/workspace/onnc-umbrella/build-normal] Make onnc failed.
Failed to execute command: 'make DESTDIR=/workspace/onnc-umbrella/install-normal install'
```

**Comment by LuisHsu** [comment]
You can try install flex and bison. `JsonScanner.cpp` is generated with them.
This information will be updated to README soon.

**Comment by Peter-Chang** [comment]
This issue is due to lack of `flex`. You can install flex in your platform to solve this issue.

**Comment by evenpengqnap** [comment]
Great, it works!
But I got the other one as following:
`/workspace/onnc-umbrella/src/lib/Target/Sophon/io.cpp:15:10: fatal error: glog/logging.h: No such file or directory`
` #include <glog/logging.h>`
`          ^~~~~~~~~~~~~~~~`
`compilation terminated.`
`Makefile:2277: recipe for target 'Target/Sophon/io.o' failed`
`make[1]: *** [Target/Sophon/io.o] Error 1`
`make[1]: Leaving directory '/workspace/onnc-umbrella/build-normal/lib'`
`Makefile:532: recipe for target 'install-recursive' failed`
`make: *** [install-recursive] Error 1`
`[/workspace/onnc-umbrella/build-normal] Make onnc failed.`
`Failed to execute command: 'make DESTDIR=/workspace/onnc-umbrella/install-normal install'`

Because I'm compiling it in a container (ubuntu:latest), I need to install a lot of packages.
Here's the packages I installed:
`apt install -y \`
`git curl cmake automake \`
`pkg-config bison byacc flex\`
`libtool protobuf-compiler libprotoc-dev \`
`python2.7 python2.7-dev python-pip `

Please check what's missing, thanks!

**Comment by Peter-Chang** [comment]
You still need install `libgoogle-glog-dev` and `libboost-dev` to avoid following issues.

**Comment by evenpengqnap** [comment]
Seems that something still missing. Suppose installing `libboost-dev` should work?
`/workspace/onnc-umbrella/build-normal/lib/libonnc.a(BM188xCodeEmitter.o): In function `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
/usr/include/boost/system/error_code.hpp:686: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:689: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:701: undefined reference to `boost::system::generic_category()'
/workspace/onnc-umbrella/build-normal/lib/libonnc.a(BM188xCodeEmitter.o): In function `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
/usr/include/boost/system/error_code.hpp:656: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:659: undefined reference to `boost::system::generic_category()'
/workspace/onnc-umbrella/build-normal/lib/libonnc.a(BM188xCodeEmitter.o):/usr/include/boost/system/error_code.hpp:206: more undefined references to `boost::system::generic_category()' follow
/workspace/onnc-umbrella/build-normal/lib/libonnc.a(BM188xCodeEmitter.o): In function `_GLOBAL__sub_I__ZN4onnc17BM188xCodeEmitterC2EPNS_13BM1880BackendERSt6vectorISt10unique_ptrINS_16ComputeOperator2ESt14default_deleteIS5_EESaIS8_EE':
/usr/include/boost/system/error_code.hpp:210: undefined reference to `boost::system::system_category()'
/workspace/onnc-umbrella/build-normal/lib/libonnc.a(Weight.o): In function `_GLOBAL__sub_I__ZN4onnc6BM188X6Weight10append8bitERSt6vectorIaSaIaEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE':
/usr/include/boost/system/error_code.hpp:206: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:208: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:210: undefined reference to `boost::system::system_category()'
/workspace/onnc-umbrella/build-normal/lib/libonnc.a(io.o): In function `__static_initialization_and_destruction_0':
/usr/include/boost/system/error_code.hpp:206: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:208: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:210: undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
Makefile:457: recipe for target 'onnc' failed
make[2]: *** [onnc] Error 1
make[2]: Leaving directory '/workspace/onnc-umbrella/build-normal/tools/onnc'
Makefile:408: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/workspace/onnc-umbrella/build-normal/tools'
Makefile:532: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
[/workspace/onnc-umbrella/build-normal] Make onnc failed.`

**Comment by evenpengqnap** [comment]
I found a temporary solution by adding `LIBS="-lz -lboost_system"` to line 181 and 183 of build.sh.

**Comment by Peter-Chang** [comment]
I think that is a right way to solve this issue. You may create a pull request to commit your code into ONNC umbrella repository.

**Comment by evenpengqnap** [comment]
Really? 
Is there a way to make auto-generated Makefile use this enviroment variables, `LIBS="-lz -lboost_system"`?

**Comment by LuisHsu** [comment]
BTW, I'm refining CMake building system with onnc main repository.
Boost and zlib will be checked and configured then, you may be interested to try it in the future.

**Comment by lubatang** [comment]
I'll remove the boost including. It looks like boost and z library  are never used.

**Comment by lubatang** [comment]
I have pushed this patch. Please help me to check if the problem has been resolved or not.
https://github.com/ONNC/onnc/commit/c593b07fce6e194b4bfbd1a6fbb4bdfeed2d2448

**Comment by evenpengqnap** [comment]
After removing boost including, `libboost-filesystem-dev` is not necessary, and the problem is resolve.
